### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by krekas** [freekmurze/laravel-analytics#10]
Getting this error message

root@debian:/var/www/laravel# composer require spatie/laravel-analytics
Using version ~1.0 for spatie/laravel-analytics
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nesbot/carbon == 1.14.0.0 -> satisfiable by nesbo              t/carbon[1.14.0].
    - spatie/laravel-analytics 1.0.1 requires php >=5.5.0 -> no matching package               found.
    - spatie/laravel-analytics 1.0.0 requires php >=5.5.0 -> no matching package               found.
    - spatie/laravel-analytics 1.0.2 requires nesbot/carbon ~1.17 -> satisfiable               by nesbot/carbon[1.17.0].
    - spatie/laravel-analytics 1.0.3 requires nesbot/carbon ~1.17 -> satisfiable               by nesbot/carbon[1.17.0].
    - Conclusion: don't install nesbot/carbon 1.17.0
    - Installation request for spatie/laravel-analytics ~1.0 -> satisfiable by s              patie/laravel-analytics[1.0.0, 1.0.1, 1.0.2, 1.0.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min              imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f              or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common               problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Could you post the contents of your composer.json file?

**Comment by krekas** [comment]
{
        "name": "laravel/laravel",
        "description": "The Laravel Framework.",
        "keywords": ["framework", "laravel"],
        "license": "MIT",
        "type": "project",
        "require": {
                "laravel/framework": "5.0.*",
                "illuminate/html": "~5.0",
                "laracasts/flash": "~1.3"
        },
        "require-dev": {
                "phpunit/phpunit": "~4.0",
                "phpspec/phpspec": "~2.1"
        },
        "autoload": {
                "classmap": [
                        "database"
                ],
                "psr-4": {
                        "App\\": "app/"
                }
        },
        "autoload-dev": {
                "classmap": [
                        "tests/TestCase.php"
                ]
        },
        "scripts": {
                "post-install-cmd": [
                        "php artisan clear-compiled",
                        "php artisan optimize"
                ],
                "post-update-cmd": [
                        "php artisan clear-compiled",
                        "php artisan optimize"
                ],
                "post-create-project-cmd": [
                        "php -r \"copy('.env.example', '.env');\"",
                        "php artisan key:generate"
                ]
        },
        "config": {
                "preferred-install": "dist"
        }
}

**Comment by MatthiasDeWinter** [comment]
I think the issue is a typo in your PSR-4 autoloader.

```javascript
"psr-4": {
"App\": "app/"
}
```
Should be:

```javascript
"psr-4": {
"App\\": "app/"
}
```
_Missing backward-slash._

I used your composer.json in a fresh Laravel 5 project, added the missing backward-slash and then the package installed as it should.

See if it works this way!

**Comment by krekas** [comment]
I don't know why it copied here without double backward-slash but it is there. Getting same error.

**Comment by MatthiasDeWinter** [comment]
Unless you have a PHP version below 5.4 I have no idea what is going wrong because the exact same composer.json installs the package fine on my end.

Maybe you can try requiring the package on a completely new Laravel installation.

If you have any new information on this error, please let let me know!

**Comment by krekas** [comment]
On fresh install works perfectly. PHP 5.4.36

**Comment by MatthiasDeWinter** [comment]
Ok,

In release 1.0.4 I lowered to minimum version of Carbon from 1.17 to 1.0 which might help avoid this issue in the future!

**Comment by krekas** [comment]
Updated carbon version to 1.17 ant know installed it without errors :)
