### ISSUE TITLE
$realTimecacheLifeTimeInMinutes Undefined Property

### ISSUE THREAD

**Issue by pgtruesdell** [freekmurze/laravel-analytics#12]
When running LaravelAnalytics::getActiveUsers() on my app I get the following error.

    ErrorException in GoogleApiHelper.php line 185:
    Undefined property: Spatie\LaravelAnalytics\GoogleApiHelper::$realTimecacheLifeTimeInMinutes

The real time component isn't working, everything else works great as far as I have used it.

**Comment by lukepolo** [comment]
Yah I get the same error, ill look into it really quick

**Comment by lukepolo** [comment]
Well there a few things wrong , if you want to fix it for now do , look at my pull request 

https://github.com/freekmurze/laravel-analytics/pull/13

**Comment by lukepolo** [comment]
Has been merged , update the package, should be good!

**Comment by freekmurze** [comment]
Version 1.1.2 solves this issue. Like @lukepolo says, just update the package to get the fix.

**Comment by pgtruesdell** [comment]
Thanks, I didn't have the time to investigate and make a pull request. 

Much appreciated!
