### ISSUE TITLE
Feature request: Laravel 4.2 support

### ISSUE THREAD

**Issue by paulofreitas** [freekmurze/laravel-analytics#14]
Hey there,

I've a large Laravel app which was developed using the Laravel 4.2 codebase. There's a lot of customizations plus various 3rd party packages not yet ready for Laravel 5, what prevents me to upgrade now. That's the package I was searching for a long time and unfortunately it only support L5.

Is there any plans to support Laravel 4.2?

Thank you anyway.

**Comment by freekmurze** [comment]
Hi,

currently there are no plans to add L4 support to laravel-analtyics. You could take a look at the [old version of this package](https://github.com/freekmurze/analytics-reports).
