### ISSUE TITLE
slow to load when running 6-8 queries 

### ISSUE THREAD

**Issue by unitedworx** [freekmurze/laravel-analytics#15]
First of all many thanks for the super package which helped us include analytics on our cms backend.

However it seems that things are slow when running 6-8 queries. Any solution to speed things up? Caching helps a lot since this delay is noticeable only when the data is refreshed but trying to figure a way to speed things up from the package itself. 

i show site statistics when a users logs in to the admin area and i want to avoid the 5-6 seconds delay when the data needs to be refreshed. The obvious solution is to load this data via an ajax call so the page loads and the data is visible as soon as they are fetched but i want to investigate if the re is a way to make these 5-6 requests to analytics API in parallel than one after the other so this will effectively take 1sec instead of 6 seconds. So even when data need to be refreshed which would be much faster.

**Comment by lukepolo** [comment]
ajax via javascript should be a preferred solution as it allows async by nature and will not hold the user in a "delay" while waiting for response

**Comment by unitedworx** [comment]
yeah i figured a good approach is to have a very long cacheLifetime so when the page load it draws my stats dashboard form the cache. and then with an ajax call i refresh each component data while doing Config::set('laravel-analytics.cacheLifetime',60 ); beforehand so that the cache for that query is refreshed 

Give it a nice touch wile graphs are being redrawn, its like an animation from the cached values to the refreshed ones! A lot more code but i think with this i solved my delay problems.

**Comment by freekmurze** [comment]
Using the Google API is indeed kinda slow. In my projects the Google API only gets called from scheduled jobs. Webrequests only show the data that was pulled in by those jobs.
