### ISSUE TITLE
(get) missing required param: 'ids'

### ISSUE THREAD

**Issue by SimonWayne** [freekmurze/laravel-analytics#16]
Hello,

i follow the documentation stp by step but i have one error:

Google_Exception in Resource.php line 163: (get) missing required param: 'ids'

**Comment by freekmurze** [comment]
Did you specify a valid siteId in the config file? It should look something like `ga:xxxxxxxx`.

**Comment by cardi777** [comment]
Love the plugin, trying to get it to work.

Im a little confused about this parameter. A normal site id looks like UA-1234567-89
Are we entering "ga:UA-1234567-89" or  "ga:1234567-89" or something else completely?

**Comment by freekmurze** [comment]
@cardi777 Look for the site Id in Google Analytics. I've provided some install instructions [in the readme](https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics)

**Comment by cardi777** [comment]
you are correct sir! thankyou

**Comment by bubacore** [comment]
Hello!! 
I have the same error
I fully followed the steps but I still dating the same mistake in Laravel 5.1:
ErrorException in Resource.php line 166:
(get) missing required param: 'ids' (View: /Users/giovanny/Sites/laravel/SC-5/resources/views/index.blade.php)

In the View is:
{!! $analyticsData = LaravelAnalytics::getVisitorsAndPageViews(7); !!}
In the config/app.php is:
'providers' =>[
Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class,]
'aliases' => [
'LaravelAnalytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class,]

Can you help me?
thanks my friend!!!

**Comment by freekmurze** [comment]
Hi,

did you add a siteId to the config file? All instructions needed are in the readme file. If you follow them to the letter, it'll work.

**Comment by usman0127** [comment]
@freekmurze 
HI , 
 can you help me to integrate google analytic in laravel 5 i follow the instruction but unable to configure it finally i get the error Google_Exception in Resource.php line 169:
(get) missing required param: 'ids' can you help me so i fix this issue thanks
