### ISSUE TITLE
GA Filters in L5.1

### ISSUE THREAD

**Issue by nam-co** [freekmurze/laravel-analytics#17]
Hi Im using php5.6 and Im trying to use the example 

$analytics = LaravelAnalytics::performQuery($numberOfDays = 365,  $others = array('filters' => 'ga:pagePath==/foods', 'dimensions' => 'ga:pagePath'));

So I can filter the results by just showing the page views to "/foods"

How can I do this? I tried many forms but I always get : Argument 1 passed to Spatie\LaravelAnalytics\LaravelAnalytics::performQuery() must be an instance of DateTime, array given, called in 

Appreciate any help
Thanks

**Comment by freekmurze** [comment]
If you look at the method signature you'll see that the performQuery-method expects 4 parameters. The first two should be DateTime-objects.

```php
 /**
     * Call the query method on the autenthicated client
     *
     * @param \DateTime $startDate
     * @param \DateTime $endDate
     * @param $metrics
     * @param array $others
     * @return mixed
     */
    public function performQuery($startDate, $endDate, $metrics, $others = array())
```php

You are passing andinteger as the first parameter, which causes the method to fail.

**Comment by nam-co** [comment]
Hi Freekmurse, thank you for your response, sorry to bother you so much, but Im lost, I tried this and still got the error, please help me , How should I put it?

$startDate = '2015-01-01 00:00:00'; $endDate = '2015-05-01 00:00:00'; $metrics = 'ga:pageviews';

$analytics = \LaravelAnalytics::performQuery($startDate, $endDate, $metrics, $others = array('filters' => 'ga:pagePath==/foods', 'dimensions' => 'ga:pagePath'));

Thanks for your help

**Comment by freekmurze** [comment]
You are passing strings while you should using [DateTime objects](http://php.net/manual/en/class.datetime.php).

**Comment by nam-co** [comment]
Hi Freekmurze sorry to bother you again, but how can I filter "getVisitorsAndPageViewsForPeriod" by specifying the path? Appreciate any help , thanks

$analytics = \LaravelAnalytics::getVisitorsAndPageViewsForPeriod($startDate, $endDate, $groupBy = 'date', $others = array('filters' => 'ga:pagePath==/Miami/Chocolate', 'dimensions' => 'ga:pagePath'));

this returns all page views and not only the ones with the path

**Comment by DigitalCoder** [comment]
Hi all !
@nam-co I've got the same needs, to filter some Paths and after with dynamic Paths to visualize then with https://github.com/ConsoleTVs/Charts

you can try this :
I use laravel-analytics 1.4 (I'm limited by my PHP version 5.6) 
In my Controller I've used this :
```
...
use Carbon\Carbon;
use ConsoleTVs\Charts\Facades\Charts as Charts;
use Spatie\LaravelAnalytics\LaravelAnalyticsFacade as LaravelAnalytics;
use Illuminate\Support\Collection;
...
```

Then :

```
		// usefull Dates helpers
		$startDate_last_week = Carbon::now()->subWeek()->startOfWeek();
		$endDate_last_week = Carbon::now()->subWeek()->endOfWeek();

		$startDate_current_week = Carbon::now()->startOfWeek();
		$endDate_current_week = Carbon::now()->endOfWeek();

		$startDate_last_month = Carbon::parse('-1 months')->startOfMonth();
		$endDate_last_month =  Carbon::parse('-1 months')->endOfMonth();

		$startDate_current_month = Carbon::now()->startOfMonth();
		$endDate_current_month = Carbon::now()->endOfMonth();

		$startDate_last_year = Carbon::parse('-1 years')->startOfYear();
		$endDate_last_year =  Carbon::parse('-1 years')->endOfYear();

		$startDate_current_year = Carbon::now()->startOfYear();
		$endDate_current_year = Carbon::now()->endOfYear();
		
		// here start your needs to specify yours paths
		$metrics = 'ga:visits,ga:pageviews'; // You can change metrics by referring to google api
		$path = 'sell'; // for example
		$filters = 'ga:pagePath==/' . $path;
		//$groupBy = 'date';
		$groupBy = 'yearMonth'; // 'yearMonth' when using Year dates start and end or 'date' when using week or month dates start and end
		$dimensions = 'ga:' . $groupBy;

		$others = array('filters' => $filters, 'dimensions' => $dimensions);
		//$answer = LaravelAnalytics::performQuery($startDate_current_month, $endDate_current_month, $metrics, $others);
		$answer = LaravelAnalytics::performQuery($startDate_current_year, $endDate_current_year, $metrics, $others);

		foreach ($answer->rows as $dateRow) {
			$visitorData[] = [$groupBy => Carbon::createFromFormat(($groupBy == 'yearMonth' ? 'Ym' : 'Ymd'), $dateRow[0]), 'visitors' => $dateRow[1], 'pageViews' => $dateRow[2]];
		}
		$analyticsDatas[$path] = new Collection($visitorData);
		var_dump($analyticsDatas[$path]->toArray());
		/*
		should return something like this :
		array(12) {
		  [0]=>
		  array(3) {
		    ["yearMonth"]=>
		    object(Carbon\Carbon)#977 (3) {
		      ["date"]=>
		      string(26) "2017-01-20 20:23:59.000000"
		      ["timezone_type"]=>
		      int(3)
		      ["timezone"]=>
		      string(3) "UTC"
		    }
		     ["visitors"]=>
		    string(2) "17"
		    ["pageViews"]=>
		    string(3) "175"
		  }
		  [1]=>
		  array(3) {
		    ["yearMonth"]=>
		    object(Carbon\Carbon)#979 (3) {
		      ["date"]=>
		      string(26) "2017-02-20 20:23:59.000000"
		      ["timezone_type"]=>
		      int(3)
		      ["timezone"]=>
		      string(3) "UTC"
		    }
		    ["visitors"]=>
		    string(1) "0"
		    ["pageViews"]=>
		    string(1) "4"
		  }
		...
		*/
		die();
```

then you can adapt to suit your needs ^^

for my charts for example :
```
		$CurrentYearVisitorsAndPageViews = $analyticsDatas[$path];
		$CurrentYearVisitorsAndPageViewsDates = $CurrentYearVisitorsAndPageViews->lists('yearMonth')->toArray();
		$CurrentYearVisitorsAndPageViewsVisitors = $CurrentYearVisitorsAndPageViews->lists('visitors')->toArray();
		$CurrentYearVisitorsAndPageViewsPageViews = $CurrentYearVisitorsAndPageViews->lists('pageViews')->toArray();

		$CurrentYearVisitorsAndPageViewsDates = array_map($formatDateByMonth, $CurrentYearVisitorsAndPageViewsDates);
		// $formatDateByMonth function return $value->format("F");
		$chartCurrentYearVisitorsAndPageViews = Charts::multi('bar', 'chartjs')
			// Setup the chart settings
			->title("Current Year Visitors And PageViews for " .$path)
			->elementLabel("Total")
			// A dimension of 0 means it will take 100% of the space
			->dimensions(0, 400) // Width x Height
			->template("material")
			// Setup the different datasets (this is a multi chart)
			->dataset('Visitors', $CurrentYearVisitorsAndPageViewsVisitors)
			->dataset('PageViews', $CurrentYearVisitorsAndPageViewsPageViews)
			// Setup what the values mean
			->labels($CurrentYearVisitorsAndPageViewsDates);
```

I hope, It would help you !
I advise you to look at the existing code in vendor **[/spatie/laravel-analytics/src/LaravelAnalytics.php](https://github.com/spatie/laravel-analytics/blob/1.4.1/src/LaravelAnalytics.php)** or **[/spatie/laravel-analytics/src/Analytics.php](https://github.com/spatie/laravel-analytics/blob/master/src/Analytics.php)**

Best regards,

enJoy & bE haPPy !

**Comment by nam-co** [comment]
DigitalCoder thanks for your post, I will try it out, have a great day

**Comment by DigitalCoder** [comment]
you're welcome!
also take a look to Google Analytics API v3 for metrics, dimensions and filters 

Regards,

**Comment by nam-co** [comment]
I did, but in my opinion they don't have the best docs, are you still using laravel charts or your planing on moving to vue-charts?

**Comment by DigitalCoder** [comment]
I just try laravel charts, easy to use with direct database requests
maybe I would use vue ou react after

**Comment by DigitalCoder** [comment]
yes You have tof search and try until to find what you really expect
I've googelized too before finding
Now I can retrieve datas from tracking events and filter with my id product ^^

**Comment by nam-co** [comment]
Hi DC, I've come back to this part in my life, I finally tried it and got this Undefined variable: formatDateByMonth, I also notice we had to change ->lists for ->pluck

**Comment by nam-co** [comment]
DC one question: did $path = '/sell' work for all the subfiles + subfolders?
for example did it include the results for:
/sell
/sell/chocolate
/sell/rum/bacardi

thanks

**Comment by higgsbenavidez** [comment]
nam-co, does it include the subfolders? I need to get all the same results as your last question. Thanks

/sell
/sell/chocolate
/sell/rum/bacardi
