### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by intrepidtr** [freekmurze/laravel-analytics#5]
Non-abstract method App\Http\Controllers\Admin\MainController::performQuery() must contain body

**Comment by intrepidtr** [comment]
Argument 1 passed to Spatie\LaravelAnalytics\LaravelAnalytics::performQuery() must be an instance of DateTime, string given, called in C:\webserver\htdocs\local\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 219 and defined

**Comment by freekmurze** [comment]
Hi, your first error probably has something to to with your MainController. Are you sure the performQuery-method there is ok?

Concerning the second error, you should pass [DateTime-objects](http://php.net/manual/en/class.datetime.php) to performQuery, instead of strings.

**Comment by intrepidtr** [comment]
ok thenks problem solved
