### ISSUE TITLE
PHP 5.4

### ISSUE THREAD

**Issue by juukie** [freekmurze/laravel-analytics#6]
Is there a special need for not supporting 5.4? google/apiclient is satisfied with >= 5.2.1 and laravel/framework >= 5.4.0..

**Comment by freekmurze** [comment]
There is no specific >= 5.4 functionality being used but 5.5 was set as a requirement with [these](http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html) [posts](http://blog.ircmaxell.com/2014/12/being-responsible-developer.html) in mind. But when looking at the [currently supported versions](http://php.net/supported-versions.php) I could indeed set 5.4 as a minmum until September.

**Comment by juukie** [comment]
If there is no specific code that needs a higher version, I would say it is a good idea to support the versions that are currently supported.
I totally agree on those blog posts but at the moment I'm having a 5.4 project and it won't be updated soon unfortunately.

**Comment by juukie** [comment]
Thanks for making the adjustment!
